### PR TITLE
Updated instructions to install Detection suite using Docker

### PR DESCRIPTION
**Pull request by sleep-404**

### CODE REVIEW

**Comment by vinay0410** [comment]
This seems fine @sleep-404 .
But also add instructions to run a sample tool like DatasetEvaluationApp.
Your current instructions only spawns the docker container, add instructions to run a sample tool.

**Comment by sleep-404** [comment]
I am trying to run the **_DatasetEvaluationApp_**  in the container but it returns 
err
But the it runs just fine on my computer with same yml file and structure.

**Comment by vinay0410** [comment]
Just post a copy of appConfig.yml.
This error occurs when your appConfig.yml doesn’t contain required keys

**Comment by vinay0410** [comment]
Hi @sleep-404 , 
This error is occurring, because DetectionSuite's docker image hasn't been updated since last year. For some reason the builds weren't triggered.
You can see the status [here](https://hub.docker.com/r/jderobot/dl-detectionsuite)

I have requested access for the same and will get it updated.

**Comment by sleep-404** [comment]
@vinay0410  I think after spawning the container one can follow the instructions [here](https://github.com/JdeRobot/dl-DetectionSuite/wiki/Beginner's-Tutorial-to-DetectionSuite-Part-1) .Because if we add any other documentation there it will not align with other parts of the page.So I think it is fine if I leave till there.
May I know your opinion ?

**Comment by vinay0410** [comment]
Okay, we can add a link to the tutorial after spawning.
But, you will have to change your existing commands so that docker can connect to display.
The run command should be changed to below, and verify if it works on your machine.
```sudo docker run -it -e DISPLAY=$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix jderobot/dl-detectionsuite```

I have updated the dockerfile and the new image will be created in an hour or so. You can start testing then.

**Comment by sleep-404** [comment]
ok

**Comment by sleep-404** [comment]
ok

**Comment by sleep-404** [comment]
@vinay0410 it works fine, tried running DatasetEvaluationapp got no errors.
But the build fails ,on checking "./install_darknet.sh" -> is the reason, even during the previous PR this happened.

**Pull request merged**
