### PR TITLE
Write Time in Auto Evalutor CSV files

### LINKED ISSUE #109: Computing time AutoEvaluator
Hi!!

I was talking to Jose and he told me that in the .csv file that is generated, the computation times should also be included. At the moment I don't need it because I've seen that on the screen if some times are shown.But I told you about it because he told me to tell you.

Regards!!

### PR DESCRIPTION
**Pull request by vinay0410**
@jessiffmm fixed #109

### CODE REVIEW

**Comment by vinay0410** [comment]
@jessiffmm , Okay I understand.
I have opened another pull request, with your commits and my changes in it.
I will merge that soon. Just review if its fine with you and works

**Comment by jessiffmm** [comment]
Hi @vinay0410 

The changes isn't uploaded no?

**Comment by vinay0410** [comment]
No,
They aren't merged yet.
I am waiting your approval/testing

**Comment by jessiffmm** [comment]
Ok but How can I download the changes that you did ?
Sorry, I haven't never done a pulll request

**Comment by vinay0410** [comment]
Just clone the repository as it is.
`git clone https://github.com/JdeRobot/dl-DetectionSuite.git`
and then run the following command as it is:
`git checkout BRANCHNAME`

Now, you have these changes, you can test and build as ususal

**Comment by jessiffmm** [comment]
Hi @vinay0410 

It works perfectly. Thanks!

**Pull request merged**
